# Network Science Project: Spectral centrality measures in temporal networks

#### Importing libraries

In [1]:
import numpy as np
import operator
import math

# Function for better visualisation

In [2]:
def OneToN(x): #Creating a vector with elements 1,2,3,4,...,n. Where n is the number of nodes.
    n=len(x)
    y=np.zeros(n)
    for i in range(n):
        y[i]=i+1
    return y

In [3]:
def NodesInOrder(vector): #Function that sorts nodes based on their scores givem by algorithm.
    Ascending=OneToN(vector)
    Dictionarry={}
    for i in range(len(vector)):
        Dictionarry[Ascending[i]]=vector[i]
    return sorted(Dictionarry.items(), key=operator.itemgetter(1),reverse=True)

In [4]:
#Netowrk in time 1-3
A13=np.array([[0,1,0,0,1,0,1],[0,0,0,1,0,0,0],[1,1,0,0,1,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[1,1,0,1,0,0,0],[1,0,0,0,1,1,0]])

In [5]:
##Netowrk in time 3-5
A35=np.array([[0,2,0,0,3,0,4],[0,0,0,5,0,0,0],[6,2,0,0,4,0,0],[0,0,0,0,0,0,0],[0,0,0,0,0,0,0],[2,1,0,5,0,0,0],[2,0,0,0,3,1,0]])

In [6]:
#Netowrk in time 5-7
A57=np.array([[0,2,0,0,3,0,4],[0,0,0,5,0,0,0],[6,2,0,0,4,0,0],[0,0,0,0,0,4,0],[0,0,0,0,0,2,0],[2,1,0,5,4,0,0],[2,0,0,0,3,1,0]])

In [7]:
#Netowrk in time 7-9
A79=np.array([[0,1,0,0,1,0,1],[0,0,0,1,0,0,0],[1,1,0,0,1,0,0],[0,0,0,0,0,1,0],[0,0,0,0,0,1,0],[1,1,0,1,1,0,0],[1,0,0,0,1,1,0]])

# Algorithm 1: Temporal Power Iteration 

#### Functions that we use in the main algorithm:

In [8]:
def MatVecRight(A,x):
    return np.dot(A,x)

In [9]:
def norm2(x):
    square_sum=0
    for i in range(x.shape[0]):
        square_sum=square_sum+pow(x[i],2)
    return np.sqrt(square_sum)

In [10]:
def normalize(x):
    return x/norm2(x)

In [11]:
def test_dif(x,y):
    z=x-y
    return norm2(z)

In [12]:
def scalProd(x,y):
    result=0
    for i in range(x.shape[0]):
        result=result+(x[i]*y[i])
    return result

#### The main algorithm:

In [86]:
def eigTemp(A,x,tol=pow(10,-6),maxIter=100):
    i=0
    convergence=False
    while i<maxIter:
        x_old=x
        x=normalize(MatVecRight(A,x)) #normalize, x eigenvector
        if test_dif(x,x_old)<tol:
            convergence=True
            break
        i=i+1
    ev=scalProd(x,MatVecRight(A,x)) #ev eigenvalue
    return x,ev,convergence    

# Algorithm 2: Temporal Eigenvalue Centrality

#### Functions that we use in the main algorithm:

In [14]:
def MatTrans(A):
    return A.T

In [15]:
def VecConst(n):
    return np.ones(n)

In [16]:
def numInv(a):
    return 1/a

In [17]:
def numVecProd(a,x):
    return a*x

#### The main algorithm:

In [18]:
def inEig(A):
    x,ev,conv=eigTemp(MatTrans(A),VecConst(A.shape[0]))
    x=numVecProd(numInv(ev),x)
    return x,conv
def outEig(A):
    x,ev,conv=eigTemp(A,VecConst(A.shape[0]))
    x=numVecProd(numInv(ev),x)
    return x,conv

In [89]:
inEig(A13)

(array([0.28929876, 0.34283015, 0.        , 0.38323959, 0.38323959,
        0.1648541 , 0.21838549]), True)

In [19]:
NodesInOrder(inEig(A13)[0])

[(4.0, 0.38323959281071945),
 (5.0, 0.38323959281071945),
 (2.0, 0.3428301504546229),
 (1.0, 0.28929875962810886),
 (7.0, 0.21838549181861674),
 (6.0, 0.1648541009921027),
 (3.0, 0.0)]

In [20]:
NodesInOrder(inEig(A35)[0])

[(5.0, 0.1977165029359666),
 (4.0, 0.1647637524466388),
 (7.0, 0.1178952801886321),
 (1.0, 0.0953793431493424),
 (2.0, 0.07020563073748974),
 (6.0, 0.0364316809314975),
 (3.0, 0.0)]

In [21]:
NodesInOrder(inEig(A57)[0])

[(4.0, 0.09060267067273253),
 (6.0, 0.08822586927649721),
 (5.0, 0.08401723940252281),
 (1.0, 0.035348776020060625),
 (2.0, 0.025354545633545576),
 (7.0, 0.022558118955545263),
 (3.0, 0.0)]

In [22]:
NodesInOrder(inEig(A79)[0])

[(6.0, 0.25055920117339614),
 (5.0, 0.23178055289678445),
 (4.0, 0.214409347589365),
 (2.0, 0.1956306993127533),
 (1.0, 0.15655198008676444),
 (7.0, 0.07522857281001999),
 (3.0, 0.0)]

In [23]:
NodesInOrder(outEig(A13)[0])

[(7.0, 0.506723582443658),
 (1.0, 0.3825140269734168),
 (3.0, 0.288751382036271),
 (6.0, 0.288751382036271),
 (2.0, 0.0),
 (4.0, 0.0),
 (5.0, 0.0)]

In [24]:
NodesInOrder(outEig(A35)[0])

[(3.0, 0.24488220399751592),
 (1.0, 0.13207579228739402),
 (7.0, 0.10685161924706503),
 (6.0, 0.08162740133250532),
 (2.0, 0.0),
 (4.0, 0.0),
 (5.0, 0.0)]

In [25]:
NodesInOrder(outEig(A57)[0])

[(6.0, 0.08622967893067747),
 (3.0, 0.08488202453068001),
 (1.0, 0.05569943615737886),
 (4.0, 0.055028057334776594),
 (7.0, 0.044698255990850956),
 (2.0, 0.043895768514011745),
 (5.0, 0.027514028667388297)]

In [26]:
NodesInOrder(outEig(A79)[0])

[(7.0, 0.267193318164005),
 (6.0, 0.23465609673068194),
 (1.0, 0.20861825590466235),
 (3.0, 0.1804710611378959),
 (4.0, 0.11276009785212866),
 (5.0, 0.11276009785212866),
 (2.0, 0.05418503559278604)]

# Algorithm 3: Temporal Jacobi Iteration

#### Functions that we use in the main algorithm:

In [27]:
def MatSetDiagVec(inverse):
    m=len(inverse)
    D=np.zeros((m,m))
    for i in range(m):
        D[i,i]=inverse[i]
    return D

In [28]:
def vecInv(vector):
    inverse=np.zeros([len(vector)])
    for i in range(len(vector)):
        inverse[i]=1/vector[i]
    return inverse

In [29]:
def diag(A):
    vector=np.zeros([A.shape[0]])
    for i in range(A.shape[0]):
        vector[i]=A[i,i]
    return vector

In [30]:
def MatMinus(A):
    return -1*A

In [31]:
def MatSetDiagZero(A):
    size=A.shape[0]
    D=np.zeros([size,size])
    for i in range(size):
        for j in range(size):
            D[i,j]=A[i,j]
    for i in range(size):
        D[i,i]=0
    return D

In [32]:
def VecSum(first,second):
    return first+second

#### The main algorithm:

In [33]:
def jacobi(A,b,x,tol=pow(10,-6),maxIter=100):
    invD=MatSetDiagVec(vecInv(diag(A)))
    B=MatMinus(MatSetDiagZero(A))
    i=0
    convergence=False
    while i<maxIter:
        i=i+1
        xn=MatVecRight(invD,VecSum(MatVecRight(B,x),b))
        if test_dif(x,xn)<tol:
            convergence=True
            break
        x=xn
    return xn,convergence

##### Testing

In [34]:
C=np.array([[1,1,1],[2,2,3],[1,-3,5]]) #random matrix C
C

array([[ 1,  1,  1],
       [ 2,  2,  3],
       [ 1, -3,  5]])

In [35]:
b=np.array([4,2,6]) #right hand side
x=np.random.rand(3) #initiate random numbers for unknow vector X
x

array([0.39773865, 0.80206569, 0.32098355])

In [36]:
result,true_false=jacobi(C,b,x)

In [37]:
result,true_false

(array([16.49999684, -6.49999896, -5.99999846]), True)

In [38]:
MatVecRight(C,result) #A*res == b?

array([3.99999942, 2.00000038, 6.00000141])

In [39]:
abs(b-MatVecRight(C,result)) #working pretty good

array([5.78483972e-07, 3.81551423e-07, 1.40882317e-06])

# Algorithm 4: Temporal Katz centrality

#### Functions that we use in the main algorithm:

In [40]:
def MatVecLeft(A,B):
    return np.dot(B,A)

In [41]:
def VecMax(x):
    return float(sum(x))

In [42]:
def MatDiff(A,B):
    return A-B

In [43]:
def MatSum(A,B):
    return A+B

#### The main algorithm:

In [44]:
def katz(A,a=None):
    n=A.shape[0]
    d=MatVecLeft(A,VecConst(n))
    maxi=0
    if a==None:
        for i in range(len(d)): 
            if VecMax(A[:,i])>maxi:
                maxi=VecMax(A[:,i])
        a=0.999/maxi
    B=1/a*np.eye(n)
    B=MatDiff(B,MatTrans(A))
    t,conv=jacobi(B,d,VecConst(n))
    m=math.factorial(n-1)*pow(a,n-1)*pow(np.exp(1),1/a)
    m=1/m
    return numVecProd(m,t),conv

In [45]:
NodesInOrder(katz(A13,0.15)[0])

[(5.0, 0.08701521909559679),
 (2.0, 0.08602060537673469),
 (1.0, 0.07938985011441337),
 (4.0, 0.06373888070803742),
 (7.0, 0.03518481798517937),
 (6.0, 0.028554062722858053),
 (3.0, 0.0)]

In [46]:
NodesInOrder(katz(A35,0.15)[0])

[(5.0, 0.5215015962375534),
 (4.0, 0.4559213070532239),
 (1.0, 0.342834378394488),
 (7.0, 0.298806005247417),
 (2.0, 0.22944660718280882),
 (6.0, 0.06809724625058437),
 (3.0, 0.0)]

In [47]:
NodesInOrder(katz(A57,0.15)[0])

[(4.0, 4.52872529768924),
 (6.0, 4.37954829572241),
 (5.0, 4.3772466717108145),
 (1.0, 1.9198856954874877),
 (2.0, 1.349127210056215),
 (7.0, 1.2449011485451351),
 (3.0, 0.0)]

In [48]:
NodesInOrder(katz(A79,0.15)[0])

[(5.0, 0.1282818514384184),
 (6.0, 0.1062280834891516),
 (2.0, 0.0994596050860777),
 (1.0, 0.09130913962461935),
 (4.0, 0.07740583713681091),
 (7.0, 0.03697271181379904),
 (3.0, 0.0)]

# Algorithm 5: Temporal Bonacich alpha centrality

#### The main algorithm:

In [91]:
def alpha(A,a, s=None):#Not working for me, i really can't find the error :/
    if s==None:
        s=VecConst(A.shape[0])
    return jacobi(np.identity(A.shape[0])-(a*(A.T)),s,VecConst(A.shape[0]))

##### Testing

In [92]:
alpha(A35,0.85)

(array([2.64220924e+44, 1.94484561e+44, 1.00000000e+00, 4.56430421e+44,
        5.47716506e+44, 1.00923413e+44, 3.26595024e+44]), False)

In [51]:
NodesInOrder(alpha(A13,0.85)[0])

[(5.0, 2664175.6544733457),
 (4.0, 2664174.8044733456),
 (2.0, 2383260.5847311434),
 (1.0, 2011127.036358026),
 (7.0, 1518154.6764232314),
 (6.0, 1146021.128050114),
 (3.0, 1.0)]

In [52]:
NodesInOrder(alpha(A35,0.85)[0])

[(5.0, 5.477165055839387e+44),
 (4.0, 4.56430421319949e+44),
 (7.0, 3.26595023702488e+44),
 (1.0, 2.6422092445360162e+44),
 (2.0, 1.9448456147568724e+44),
 (6.0, 1.0092341260235758e+44),
 (3.0, 1.0)]

In [53]:
NodesInOrder(alpha(A57,0.85)[0])

[(4.0, 1.0561031039951371e+73),
 (6.0, 1.0283971904927055e+73),
 (5.0, 9.793404252479036e+72),
 (1.0, 4.120403866403615e+72),
 (2.0, 2.9554317897573465e+72),
 (7.0, 2.62946665246507e+72),
 (3.0, 1.0)]

In [54]:
NodesInOrder(alpha(A79,0.85)[0])

[(6.0, 2.3012704045561674e+25),
 (5.0, 2.1287973770505854e+25),
 (4.0, 1.96925066413978e+25),
 (2.0, 1.7967776366341986e+25),
 (1.0, 1.4378579899897374e+25),
 (7.0, 6.90939387060848e+24),
 (3.0, 1.0)]

# Algorithm 6: Bonacich (alpha,beta) centrality

#### The main algorithm:

In [55]:
def bonacich(A,b,a=None):
    normB=False
    if a==None:
        a=1
        normB=True
    b1=numVecProd(a,MatVecRight(A,VecConst(A.shape[0])))
    B=MatSum(np.identity(A.shape[0]),-b*A)
    x,conv=jacobi(B,b1,VecConst(A.shape[0]))
    if normB:
        x=numVecProd(np.sqrt(A.shape[0]),normalize(x))
    return x,conv

##### Testing

In [56]:
NodesInOrder(bonacich(A13,0.15)[0])

[(7.0, 1.4104424003845288),
 (1.0, 1.2892726381711272),
 (3.0, 1.2710971758218697),
 (6.0, 1.2710971758218697),
 (2.0, 0.34212897991273156),
 (4.0, 0.0),
 (5.0, 0.0)]

In [57]:
NodesInOrder(bonacich(A35,0.15)[0])

[(3.0, 1.9514280499813526),
 (1.0, 1.2052598669579724),
 (6.0, 0.9233241858397826),
 (7.0, 0.8852739968468359),
 (2.0, 0.3209978460933312),
 (4.0, 0.0),
 (5.0, 0.0)]

In [58]:
NodesInOrder(bonacich(A57,0.15)[0])

[(3.0, 1.427626109592854),
 (6.0, 1.4249361893716217),
 (1.0, 0.9386029386842797),
 (4.0, 0.8892820324670281),
 (7.0, 0.7469676528960576),
 (2.0, 0.7099128325802996),
 (5.0, 0.44464101623351404)]

In [59]:
NodesInOrder(bonacich(A79,0.15)[0])

[(6.0, 1.4700311721322585),
 (7.0, 1.2895542936151132),
 (1.0, 1.1432910493683042),
 (3.0, 1.1213515645574232),
 (4.0, 0.4949428518216443),
 (5.0, 0.4949428518216443),
 (2.0, 0.34867960757483535)]

# Algorithm 7: Power iteration for computing the eigenvalues of A.T*A

#### Functions that we use in the main algorithm:

In [60]:
def MatTransVecRight(A,x):
    return np.dot(A.T,x)

#### The main algorithm:

In [61]:
def singTemp(A,x,tol=pow(10,-6),maxIter=100):
    i=0
    convergence=False
    while i<maxIter:
        x_old=x
        x=normalize(MatTransVecRight(A,MatVecRight(A,x)))
        if test_dif(x,x_old)<tol:
            convergence=True
            break
        i=i+1
    ev=scalProd(x,MatTransVecRight(A,MatVecRight(A,x)))
    return x,ev,convergence

# Algorithm 8: Hubs and authorities (HITS Algorithm)

#### The main algorithm:

In [62]:
def hits(A):
    y,evy,conv=singTemp(A,VecConst(A.shape[0]))
    x=normalize(MatVecRight(A,y))
    evInv=numInv(evy)
    y=numVecProd(evInv,y)
    x=numVecProd(evInv,x)
    return x,y,conv

##### Testing

In [63]:
NodesInOrder(hits(A13)[0])

[(3.0, 0.07813945527502619),
 (6.0, 0.06150098818767857),
 (1.0, 0.059857806195413595),
 (7.0, 0.059857806195413595),
 (2.0, 0.009264596969477372),
 (4.0, 0.0),
 (5.0, 0.0)]

In [64]:
NodesInOrder(hits(A35)[0])

[(3.0, 0.00992624759750904),
 (7.0, 0.004464306426780718),
 (6.0, 0.0043351296874453845),
 (1.0, 0.0041096146404701024),
 (2.0, 0.001987414184883836),
 (4.0, 0.0),
 (5.0, 0.0)]

In [65]:
NodesInOrder(hits(A57)[0])

[(3.0, 0.006357327612411748),
 (6.0, 0.005812859783106858),
 (7.0, 0.003082619239216009),
 (1.0, 0.0028761463042818883),
 (2.0, 0.0018798058771986642),
 (4.0, 0.00014981125504580142),
 (5.0, 7.490562752290071e-05)]

In [66]:
NodesInOrder(hits(A79)[0])

[(6.0, 0.06282082031012431),
 (3.0, 0.05547216308327821),
 (7.0, 0.04448142399956215),
 (1.0, 0.04292015098147593),
 (2.0, 0.0073486572268461016),
 (4.0, 0.005892671334141675),
 (5.0, 0.005892671334141675)]

In [67]:
NodesInOrder(hits(A13)[1])

[(1.0, 0.07218403342215594),
 (2.0, 0.07218403342215593),
 (5.0, 0.07158946466281137),
 (4.0, 0.02560498387011615),
 (6.0, 0.021658216557721894),
 (7.0, 0.021658216557721894),
 (3.0, 0.0)]

In [68]:
NodesInOrder(hits(A35)[1])

[(1.0, 0.008651661490188174),
 (5.0, 0.007336401090878623),
 (2.0, 0.003633830515415609),
 (4.0, 0.003544790312388904),
 (7.0, 0.0018432689486385183),
 (6.0, 0.0005005894365912132),
 (3.0, 0.0)]

In [69]:
NodesInOrder(hits(A57)[1])

[(5.0, 0.006580243340381865),
 (1.0, 0.00553007379502031),
 (4.0, 0.0038027262006044074),
 (2.0, 0.002400452555040212),
 (7.0, 0.0011374145980066043),
 (6.0, 0.00037882314845527225),
 (3.0, 0.0)]

In [70]:
NodesInOrder(hits(A79)[1])

[(5.0, 0.06656603801507417),
 (1.0, 0.05267639628760718),
 (2.0, 0.05217113325771372),
 (4.0, 0.02270795804629237),
 (6.0, 0.01820884133055525),
 (7.0, 0.013889641727466992),
 (3.0, 0.0)]

# Algorithm 9: The temporal PageRank algorithm

#### Functions that we use in the main algorithm:

In [71]:
def vecInvPR1(s,A):
    n=len(s)
    index=[]
    for i in range(len(s)):
        if s[i]==0:
            index.append(i)
    D=np.dot(MatSetDiagVec(vecInv(s)),A)
    for i in index:
        D[i,:]=1/n
    return D

In [72]:
def DiagMatProd(x,A):
    n=len(x)
    G=np.zeros([n,n])
    for i in range(n):
        G[i,i]=x[i]
    return np.dot(G,A)

In [73]:
def constantMat(n,m):
    A=m*np.ones([n,n])
    return A

In [74]:
def norm1(x):
    n=len(x)
    total=0
    for i in range(n):
        total=total+x[i]
    return x/total

#### The main algorithm:

In [75]:
def pageRank(A,q=0.15):
    n=A.shape[0]
    S=np.zeros([n,n])
    s=MatVecRight(A,VecConst(n))
    S=vecInvPR1(s,A)    
    M=q/n*np.ones([n,n])+(1-q)*S
    x,ev,conv=eigTemp(MatTrans(M),VecConst(n))
    x=norm1(x)
    return x,conv

In [76]:
pageRank(A13)

C:\Users\giaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  after removing the cwd from sys.path.


(array([0.15107022, 0.16185577, 0.07020052, 0.23673982, 0.16491165,
        0.10221824, 0.11300379]), True)

In [77]:
NodesInOrder(pageRank(A13)[0])

C:\Users\giaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  after removing the cwd from sys.path.


[(4.0, 0.23673981724129228),
 (5.0, 0.16491165217601284),
 (2.0, 0.16185576702968474),
 (1.0, 0.15107022153276267),
 (7.0, 0.1130037854997067),
 (6.0, 0.10221824000278465),
 (3.0, 0.07020051651775622)]

In [78]:
NodesInOrder(pageRank(A35)[0])

C:\Users\giaw\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in double_scalars
  after removing the cwd from sys.path.


[(4.0, 0.2252497396131958),
 (5.0, 0.19494269671728723),
 (1.0, 0.16033432938779257),
 (7.0, 0.1330227636150867),
 (2.0, 0.12270167223815273),
 (6.0, 0.09129683159234732),
 (3.0, 0.07245196683613755)]

In [79]:
NodesInOrder(pageRank(A57)[0])

[(6.0, 0.36197319746999307),
 (4.0, 0.20801783563595455),
 (5.0, 0.18285428471335385),
 (1.0, 0.09842135733839003),
 (2.0, 0.06869474713644604),
 (7.0, 0.05861000627729119),
 (3.0, 0.02142857142857143)]

In [80]:
NodesInOrder(pageRank(A79)[0])

[(6.0, 0.33280161964851196),
 (4.0, 0.20294550202358846),
 (5.0, 0.14552342294189938),
 (2.0, 0.13034888958695798),
 (1.0, 0.11339490360670149),
 (7.0, 0.05355709076376934),
 (3.0, 0.02142857142857143)]